---
- name: Install Docker
  hosts: all
  
  tasks:
    - name: update pkgs
      become: true
      apt:
        update_cache: yes
        force_apt_get: yes
    - name: Install packages to allow apt to use a repository over HTTPS
      become: true
      apt:
        pkg: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gnupg2
    - name: Add Docker's official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key --keyring /etc/apt/trusted.gpg.d/docker.gpg add -
    - name: Add the Docker Apt Repo
      shell: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - name: update pkgs after docker repo addtion
      become: true
      apt:
        update_cache: yes
        force_apt_get: yes  
    - name: Install Docker pkgs
      become: true
      apt:
        pkg:
          - docker